name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci
      
      - name: Deploy to Vercel 🚀
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # You'll need to add this secret in your repo
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # You'll need to add this secret in your repo
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # You'll need to add this secret in your repo
          working-directory: ./
          vercel-args: '--prod'  # Deploy to production
